<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Boulevard.MarketData.Engine\Boulevard.MarketData.Engine.csproj" />
    <ProjectReference Include="..\..\Protocols\Boulevard.Protocol.Itch\Boulevard.Protocol.Itch.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
